# Generated by Django 4.2.16 on 2024-11-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('OWN', 'Propio'), ('SUP', 'Proveedor')], default='OWN', max_length=3),
        ),
    ]
