# Generated by Django 4.2.16 on 2024-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_proveedor_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_products',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='products.product'),
        ),
    ]
